package CustomObjects;

// A custom class that allows a service ticket object to be generated by a user,
// added to a list of current tickets, and assigned to a service technician.
public class Ticket {
	
	// An enum used to declare the severity of an issue associated with a ticket.
	public static enum Severity {
		LOW, MEDIUM, HIGH;
	}
	
	// An enum used to declare the service desk level that a ticket should be issued to.
	public static enum Level {
		ONE, TWO;
	}
	
	// Declare variables used to store ticket information.
	private String description;
	private int staffID;
	private int technicianID;
	
	// Declare a severity variable for this ticket.
	private Severity severity;
	
	// Delcare a service desk level for this ticket.
	private Level level;
	
	// Constructor for ticket object.
	public Ticket(String description, int staffID, int technicianID,
					Severity severity, Level level) {
			
			// Contains a description of the issue, the ID of the staff member that
			// created the ticket, the ID of the technician it has been issued to, the 
			// severity of the issue, and the service desk level for it to be issued to.
			this.description = description;
			this.staffID = staffID;
			this.technicianID = technicianID;
			this.severity = severity;
			this.level = level;
	}
	
	// Increase the service desk level of the ticket.
	public void increaseLevel() {
		if (this.level.equals(Level.ONE)) {
			this.level = Level.TWO;
		} else {
			System.out.println("Ticket is already at max level");
		}
	}
	
	// Decrease the service desk level of the ticket.
	public void decreaseLevel() {
		if (this.level.equals(Level.TWO)) {
			this.level = Level.ONE;
		} else {
			System.out.println("Ticket is already at min level");
		}
	}
	
	// Display ticket information over several lines.
	public void display() {
		System.out.printf("%s%-15s\n"
							+"%s%-15f\n"
							+"%s%-15f\n"
							+"%s%-15s\n"
							+"%s%-15s\n", 
							"Description: " + this.description,
							"Ticket Creator: " + this.staffID,
							"Assigned Tech: " + this.technicianID,
							"Ticket Severity: " + this.severity.toString(),
							"Service Desk: Level " + this.level.toString());
}
	
	// Get & Set
	public  Level getLevel() {
		return this.level;
	}
	
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public Severity getSeverity() {
		return this.severity;
	}
	
	public void setSeverity(Severity severity) {
		this.severity = severity;
	}
	
	public int getStaffID() {
		return this.staffID;
	}
	
	public void setStaffID(int staffID) {
		this.staffID = staffID;
	}
	
	public int getTechnicianID() {
		return this.technicianID;
	}
	
	public void setTechnicianID(int technicianID) {
		this.technicianID = technicianID;
	}
	
}
