package CustomObjects;

// A custom class that allows a service ticket object to be generated by a user,
// added to a list of current tickets, and assigned to a service technician.
public class Ticket {
	
	// An enum used to declare the severity of an issue associated with a ticket.
	public static enum Severity {
		LOW, MEDIUM, HIGH;
	}
	
	// An enum used to declare the service desk level that a ticket should be issued to.
	public static enum Level {
		ONE, TWO;
	}
	
	public static enum Status {
		NEW, IN_PROGRESS, RESOLVED;
	}
	
	// Declare variables used to store ticket information.
	private static int ticketIDGenerator;
	private String description;
	private int ticketID;
	private int staffID;
	private int technicianID;
	
	// Declare a severity variable for this ticket.
	private Severity severity;
	
	// Decare a service desk level for this ticket.
	private Level level;
	
	// Declare a status variable.
	private Status status;
	
	// Constructor for ticket object.
	public Ticket(String description, int staffID, int technicianID,
					Severity severity, Level level) {
			
			// Contains a description of the issue, the ID of the staff member that
			// created the ticket, the ID of the technician it has been issued to, the 
			// severity of the issue, and the service desk level for it to be issued to.
			this.ticketID = ++ticketIDGenerator;
			this.description = description;
			this.staffID = staffID;
			this.technicianID = technicianID;
			this.severity = severity;
			this.level = level;
			this.status = Status.NEW;
	}
	
	// To increase the severity level of a service ticket
	public boolean increaseSeverityLevel() {
		if (!this.severity.equals(Severity.HIGH)) {
			if(this.severity.equals(Severity.LOW)) {
				this.severity = Severity.MEDIUM;
				return true;
			} else if (this.severity.equals(Severity.MEDIUM)) {
				this.severity = Severity.HIGH;
				return true;
			}
		} else {
			System.out.println("\nError. Ticket severity level is already at maxium.");
			return false;
		}
		return false;
	}
	
	// To decrease the level of a service ticket
	public boolean decreaseSeverityLevel() {
		if (!this.severity.equals(Severity.LOW)) {
			if (this.severity.equals(Severity.HIGH)) {
				this.severity = Severity.MEDIUM;
				return true;
			} else if (this.severity.equals(Severity.MEDIUM)) {
				this.severity = Severity.HIGH;
				return true;
			}
		} else {
			System.out.println("\nError. Ticket level is already at minimum.");
			return false;
		}
		return false;
	}
	
	// Increase the service desk level of the ticket.
	public void increaseDeskLevel() {
		if (this.level.equals(Level.ONE)) {
			this.level = Level.TWO;
		} else {
			System.out.println("Ticket is already at max level");
		}
	}
	
	// Decrease the service desk level of the ticket.
	public void decreaseDeskLevel() {
		if (this.level.equals(Level.TWO)) {
			this.level = Level.ONE;
		} else {
			System.out.println("Ticket is already at min level");
		}
	}
	
	public Status getStatus() {
		return this.status;
	}
	
	public void setStatus(Status status) {
		this.status = status;
	}
	
	// Display ticket information over several lines.
		public void display() {
			
//			System.out.printf("%s%d\n%s%d\n%s%d\n%s%s\n%s%s\n%s%s\n",
//								"Ticket ID: " + this.ticketID,
//								"Ticket Creator: " + this.staffID,
//								"Assigned Tech: " + this.technicianID,
//								"Description: " + this.description,
//								"Ticket Severity: " + this.severity,
//								"Service Desk: Level " + this.level);
			
			
			System.out.println("\nTicket ID: " + this.ticketID + "\nTicket Creator: " + this.staffID
								+ "\nAssigned Tech: " + this.technicianID + "\nDescription: " + this.description
								+ "\nTicket Severity: " + this.severity.toString() + "\nService Desk: Level " + this.level.toString() + "\n");
		}
	
	// Get & Set
	public int getID() {
		return this.ticketID;
	}
		
	public  Level getLevel() {
		return this.level;
	}
   	public void setLevel(Level level) {
        	this.level = level;
    	}
	public String getDescription() {
		return this.description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public Severity getSeverity() {
		return this.severity;
	}
	
	public void setSeverity(Severity severity) {
		this.severity = severity;
	}
	
	public int getStaffID() {
		return this.staffID;
	}
	
	public void setStaffID(int staffID) {
		this.staffID = staffID;
	}
	
	public int getTechnicianID() {
		return this.technicianID;
	}
	
	public void setTechnicianID(int technicianID) {
		this.technicianID = technicianID;
	}
	
}
